# 工作流名称
name: Docker
on:
  push:
    branches: 
      - master
    tags:
      - 'v*'
env:
  # 仓库地址
  REGISTRY: docker.io
  DOCKER_NAME: 8720826 
  IMAGE_TAG: v1.0
  PROJECT_NAME: linkbox
  PORT: 5274

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Build the Docker image
        run: |
          docker version
          docker login --username={{ env.DOCKER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }} {{ env.REGISTRY }}
          docker build . --file ./Dockerfile --tag {{ env.REGISTRY }}/{{ env.DOCKER_NAME }}/{{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }}.${{github.run_number}}
          docker push {{ env.REGISTRY }}/{{ env.DOCKER_NAME }}/{{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }}.${{github.run_number}}
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  
          username: ${{ secrets.SERVER_USERNAME }} 
          password: ${{ secrets.SERVER_PASSWORD }} 
          port: ${{ secrets.SERVER_PORT }} 
          script: |
            docker login --username={{ env.DOCKER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }} {{ env.REGISTRY }}
            if docker ps -a | grep -q {{ env.PROJECT_NAME }}; then
                docker stop {{ env.PROJECT_NAME }}
                docker rm {{ env.PROJECT_NAME }}
            fi
            docker run --name {{ env.PROJECT_NAME }} -d  -p {{ env.PORT }}:80 {{ env.REGISTRY }}/{{ env.DOCKER_NAME }}/{{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }}.${{github.run_number}}
