# 工作流名称
name: Docker
on:
  push:
    branches: 
      - master
    tags:
      - 'v*'
env:
  # 仓库地址
  REGISTRY: docker.io
  IMAGE_NAME: 8720826/linkbox 
  IMAGE_TAG: v1.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4 


      - name: Build the Docker image
        run: |
          docker version
          docker login --username=8720826 --password=${{ secrets.DOCKER_PASSWORD }} docker.io
          docker build . --file ./Dockerfile --tag docker.io/8720826/linkbox:${{ env.IMAGE_TAG }}.${{github.run_number}}
          docker push docker.io/8720826/linkbox:${{ env.IMAGE_TAG }}.${{github.run_number}}
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}    
          username: ${{ secrets.SERVER_USERNAME }} 
          password: ${{ secrets.SERVER_PASSWORD }}  
          port: ${{ secrets.SERVER_PORT }}  
          script: |
            docker login --username=8720826 --password=${{ secrets.DOCKER_PASSWORD }} docker.io
            if docker ps -a | grep -q linkbox; then
                docker stop linkbox
                docker rm linkbox
            fi
            docker run -d -p 50083:8080 --name linkbox --privileged -u root -e LANG=en_US.UTF-8 --restart=always -e TZ=Asia/Shanghai -v /etc/linkbox:/app -d docker.io/8720826/linkbox:${{ env.IMAGE_TAG }}.${{github.run_number}}
